[package]
name = "vmm-fdt"
version = "0.1.0"
authors = ["Qiu Wenbo <qiuwenbo@phytium.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
